version: '3.8'
services:
  redis:
    image: redis:7.2.2
    ports:
      - "6379:6379"

  personalisation-tool:
    image: some.registry.com/xr2learn-enablers/personalisation-tool:latest
    build:
      context: 'Personalisation_Tool'
      dockerfile: 'Dockerfile'
    volumes:
      - "./Personalisation_Tool:/app"
    working_dir: /app
    environment:
      - REDIS_HOST=${REDIS_HOST}
    command: python personalisation_tool/suggest_activity_level.py
    depends_on:
      - redis

