services:
  redis:
    image: redis:7.2.2
    ports:
      - "6379:6379"

  personalization-tool:
    image: ghcr.io/xr2learn/personalization-tool:latest
    build:
      context: 'Personalization_Tool'
      dockerfile: 'Dockerfile'
    volumes:
      - "./Personalization_Tool:/app"
    working_dir: /app
    environment:
      - REDIS_HOST=redis
    command: python personalization_tool/suggest_activity_level.py
    depends_on:
      - redis

  dashboard:
    image: ghcr.io/xr2learn/dashboard:latest
    build:
      context: 'Personalization_Dashboard'
      dockerfile: 'Dockerfile'
    volumes:
      - "./Personalization_Dashboard:/app"
    working_dir: /app
    environment:
      - REDIS_HOST=redis
    command: python web_app.py
    depends_on:
      - redis
      - personalization-tool
    ports:
      - "8000:8000"

  fusion-layer:
    image: ghcr.io/xr2learn/fusion-layer:latest
    volumes:
      - "./datasets:/app/datasets"
      - "./outputs:/app/outputs"
      - "${CONFIG_FILE_PATH:-./configuration.json}:/app/configuration.json"
    working_dir: /app
    environment:
      - EXPERIMENT_ID=${EXPERIMENT_ID:-development-model}
      - REDIS_HOST=redis
      - PUBLISHER_ON=${PUBLISHER_ON:-true}
    command: python multimodal_fusion_layer/predict.py
    depends_on:
      - redis

