version: '3.8'
services:
  redis:
    image: redis:7.2.2
    ports:
      - "6379:6379"

  personalisation-tool:
    image: some.registry.com/xr2learn-enablers/personalisation-tool:latest
    build:
      context: 'Personalisation_Tool'
      dockerfile: 'Dockerfile'
    volumes:
      - "./Personalisation_Tool:/app"
    working_dir: /app
    environment:
      - REDIS_HOST=redis
    command: python personalisation_tool/suggest_activity_level.py
    depends_on:
      - redis

  demo-ui:
    image: some.registry.com/xr2learn-enablers/demo-ui:latest
    build:
      context: 'DemoUI'
      dockerfile: 'Dockerfile'
    volumes:
      - "./DemoUI:/app"
    working_dir: /app
    environment:
      - REDIS_HOST=redis
    command: python web_app.py
    depends_on:
      - redis
      - personalisation-tool
    ports:
      - "8000:8000"

  fusion-layer:
    image: some.registry.com/xr2learn-enablers/fusion-layer:latest
    volumes:
      - "./datasets:/app/datasets"
      - "./outputs:/app/outputs"
      - "${CONFIG_FILE_PATH:-./configuration.json}:/app/configuration.json"
    working_dir: /app
    environment:
      - EXPERIMENT_ID=${EXPERIMENT_ID:-development-model}
      - REDIS_HOST=redis
      - PUBLISHER_ON=${PUBLISHER_ON:-true}
    command: python multimodal_fusion_layer/predict.py
    depends_on:
      - redis

